### PR TITLE
Work status

### PR DESCRIPTION
**Pull request by satya-vinay**

### CODE REVIEW

**Comment by rrmerugu** [comment]
please remove the *.pyc files and add "*.pyc" to the .gitignore file.

**Comment by rrmerugu** [comment]
Did you implement any actual code in the django project you sent? i dont see any code that you might have written ?

**Comment by vramana** [comment]
@rrmerugu You can write .gitignore at the root of git repo and it would apply to all.

**Comment by vramana** [comment]
@satya-vinay You should not send PR from master branch. You have to create seperate branch and then commit your work there and send the PR.

**Comment by rrmerugu** [comment]
@vramana  the point here is make them aware of the rookie mistakes.

**Comment by rrmerugu** [comment]
@vramana  regards the PR, you have a very valid point, ideally thats how PR should be.  I will ask people to implement that way.

**Pull request closed without merging**
